### ISSUE TITLE
使用你那个表格的时候，第二次展示表格的时候发现，有些列宽自适应的宽度存在问题

### ISSUE THREAD

**Issue by longlonggi** [legendJaden/AFTableColumn#1]
使用场景，聊天对话框，当用户搜索员工人数的时候，机器人回复关于员工人数的表格，第一次选择表格，自适应宽度正常，当第二次用户搜索员工人数的时候，这时候回复的关于员工人数表格，出现某列的宽度比之前的宽度还要大，但是内容却是一样的情况

**Comment by legendJaden** [comment]
@longlonggi 可以贴个代码么, 有个 demo 最好了~

**Comment by longlonggi** [comment]
我在项目中是按需加载，而且在<af-table-column label="列1" prop="field1"></af-table-column>还需要加入：show-overflow-tooltip="true" 要不然会换行

**Comment by legendJaden** [comment]
@longlonggi 没有复现你的问题哦。

**Comment by susuie** [comment]
我也遇到这个问题
![image](https://user-images.githubusercontent.com/32892344/67078446-e38b8880-f1c3-11e9-9438-bb3cb887e9a5.png)
