### ISSUE TITLE
对 elementUI 自带的 size 有影响

### ISSUE THREAD

**Issue by Jessiejy** [legendJaden/AFTableColumn#2]
使用后，定义element size为small的组件边距错乱了

**Comment by legendJaden** [comment]
1. 请问是对哪个组件使用了 `size="small"` 呢?
2. 边距错乱是怎么个错乱法呢? 有截图可以看下吗? 如果能贴上相关代码最好了.

我在 table 和 button 上都试了 size small, 没有发现什么异常.
