### ISSUE TITLE
无法使用自定义内容

### ISSUE THREAD

**Issue by zhengyanbin-yy** [legendJaden/AFTableColumn#3]
无法使用以下写法
<af-table-column label="操作">
      <template slot-scope="scope">
        <el-button @click="removeItem">删除</el-button>
      </template>
    </af-table-column>

**Comment by legendJaden** [comment]
button 是支持的, 这是该项目示例中的代码
```vue
    <af-table-column label="贴边 (自定义)" fixed="right">
      <template slot-scope="scope">
        <el-button>{{scope.row.fix}}</el-button>
      </template>
    </af-table-column>
```

是否有放到 `<template></template>` 中呢?
