### ISSUE TITLE
建议更新 vue 和 vue-template-compiler到最新版本

### ISSUE THREAD

**Issue by nanlei2000** [legendJaden/AFTableColumn#4]
你好,你的组件很好,但是用在项目中会报错.原因是上述的两个包之前版本对 scope slot 有 bug.见此 [issue](https://github.com/vuejs/vue/issues/9863#issuecomment-482393518)

**Comment by legendJaden** [comment]
多谢提醒, 已经都更新为 2.6.10 版本.

**Comment by legendJaden** [comment]
请将 af-table-column 更新到 @1.0.3 版本, 谢谢.
