### ISSUE TITLE
建议字体大小可配置

### ISSUE THREAD

**Issue by CCTV-lulu** [legendJaden/AFTableColumn#9]
我的表格表头部分的字体大小是16px，并且字体有加粗，导致自适应的效果不太完美，如果字体大小部分可以在使用组件时配置就更好了。同时表示感谢，解我燃眉之急。

**Comment by legendJaden** [comment]
可以试试组件中的 fontSize 属性

**Comment by legendJaden** [comment]
同样感谢你的支持.
